In [1]:
import numpy as np


In [2]:
arr = np.arange(0,10)

In [3]:
#Basic Arithmetic
print(arr + arr)
print(arr * arr)
print(arr-arr)
print(arr / arr) #division by zero (0/0=nan)
print(arr ** 3)
print(np.sqrt(arr))


[ 0  2  4  6  8 10 12 14 16 18]
[ 0  1  4  9 16 25 36 49 64 81]
[0 0 0 0 0 0 0 0 0 0]
[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[  0   1   8  27  64 125 216 343 512 729]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


C:\Users\dbda.STUDENTSDC\AppData\Local\Temp\ipykernel_9436\4223745855.py:5: RuntimeWarning: invalid value encountered in divide
  print(arr / arr) #division by zero (0/0=nan)


In [4]:
#Summary Statistics
print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min())
print(arr.var())
print(arr.std())

45
4.5
9
0
8.25
2.8722813232690143


In [5]:
#Reversing an array
arr = np.array([1, 2, 3, 4, ])
reversed_arr = arr[::-1]
print(reversed_arr)

[4 3 2 1]


In [6]:
#Sorting an array
arr = np.array([5, 2, 8, 1 , 3])
sorted_arr = np.sort(arr)
print(sorted_arr)

[1 2 3 5 8]


In [7]:
#For Descending
sorted_arr = np.sort(arr[::-1]) #Reverse the array
print(sorted_arr)

[1 2 3 5 8]


In [8]:
#Creating multi-dimensional arrays as a "structure"

students = np.array([
    ('Alice', 95, 20),
    ('Bob', 88, 21),
    ('Charlie', 92, 19)],dtype=[('name', 'U10'),('marks', 'i4'), ('age', 'i4')])

print(students)
print(students['name'])
print(students['marks'])
print(students['marks'].mean())
print(students[students['name'] == 'Alice']['marks'])
print(students[students['name'] == 'Alice']['marks'][0])

[('Alice', 95, 20) ('Bob', 88, 21) ('Charlie', 92, 19)]
['Alice' 'Bob' 'Charlie']
[95 88 92]
91.66666666666667
[95]
95


In [10]:
sales = [0, 5, 155, 0, 518, 616]
sales_array = np.array(sales)

In [11]:
print(type(sales_array))
print(sales_array.ndim)
print(sales_array.shape)
print(sales_array.size)
print(sales_array.dtype)

<class 'numpy.ndarray'>
1
(6,)
6
int32


In [12]:
#where() function
result_array = np.where(sales_array ==0, "No Sales", "Some sales")
print(result_array)

['No Sales' 'Some sales' 'Some sales' 'No Sales' 'Some sales' 'Some sales']


In [13]:
#Show all boolean values where condition is applied
bool_mask = sales_array!= 0
print(bool_mask)

[False  True  True False  True  True]


In [14]:
#Filter using the boolean mask
filtered_sales = sales_array[bool_mask]
print(filtered_sales)

[  5 155 518 616]
